// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// A comment on a blog post.
type Comment struct {
	ID     string `json:"id"`
	Body   string `json:"body"`
	Author *User  `json:"author"`
	Post   *Post  `json:"post"`
}

// Root mutation operations.
type Mutation struct {
}

// Input for creating a new comment.
type NewComment struct {
	Body     string `json:"body"`
	AuthorID string `json:"authorId"`
	PostID   string `json:"postId"`
}

// Input for creating a new blog post.
type NewPost struct {
	Title    string `json:"title"`
	Body     string `json:"body"`
	AuthorID string `json:"authorId"`
}

// A blog post with a title, body, author, and comments.
type Post struct {
	ID       string     `json:"id"`
	Title    string     `json:"title"`
	Body     string     `json:"body"`
	Author   *User      `json:"author"`
	Comments []*Comment `json:"comments"`
}

// Root query operations.
type Query struct {
}

// A user who writes posts and comments.
type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
